# Generated by Django 5.0.6 on 2024-09-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_shipposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipposition',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.game'),
        ),
    ]
