# Generated by Django 5.0.6 on 2024-09-14 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_game_board_game_ship_positions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ship_positions',
        ),
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_turn_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_positions', models.JSONField(default=list)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player_1_board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1_board', to='application.board'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2_board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2_board', to='application.board'),
        ),
    ]
