# Generated by Django 5.0.6 on 2024-09-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_game_ship_positions_alter_game_current_turn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='ship_positions',
            field=models.TextField(default=''),
        ),
    ]
