# Generated by Django 5.0.6 on 2024-09-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
